---
- name: CentOS 7 Install Block
  block:

  - name: install centos 7 docker dependencies
    yum:
      name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: present

  - name: check for docker repo
    stat:
      path: /etc/yum.repos.d/docker-ce.repo
    register: docker_ce_repo

  - name: install docker-ce.repo if not found
    when: docker_ce_repo.stat.exists | bool == false
    import_tasks: ../../repos/tasks/docker.yml

  - name: install docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: enable docker
    service:
      name: docker
      enabled: true

  - name: start docker
    service:
      name: docker
      state: started

  - name: install docker-compose
    yum:
      name: docker-compose
      state: present

  when:
    - install_docker | bool == true
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  become: true
  become_method: sudo

- name: CentOS 7 Uninstall Block
  block:

  - name: uninstall docker-compose
    yum:
      name: docker-compose
      state: absent

  - name: stop docker
    service:
      name: docker
      state: stopped

  - name: uninstall docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: absent

  when:
    - install_docker | bool == false
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  become: true
  become_method: sudo

- name: Fedora 32+ uninstall old versions and dependencies of docker
  block:
  - name: remove fedora old version and dependencies of docker
    dnf:
      name:
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-selinux
        - docker-engine-selinux
        - docker-engine
      state: absent
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version >= "32"
  become: true
  become_method: sudo

- name: Fedora 32+ Install Block
  block:

  - name: install fedora docker dependencies
    dnf:
      name:
        - dnf-plugins-core
      state: present

  - name: check for docker repo
    stat:
      path: /etc/yum.repos.d/docker-ce.repo
    register: docker_ce_repo

  - name: install docker-ce.repo if not found
    when: docker_ce_repo.stat.exists | bool == false
    import_tasks: ../../repos/tasks/docker.yml

  - name: install docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: enable docker
    service:
      name: docker
      enabled: true

  - name: start docker
    service:
      name: docker
      state: started

  - name: install docker-compose
    dnf:
      name: docker-compose
      state: present

  when:
    - install_docker | bool == true
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version >= "32"
  become: true
  become_method: sudo
