---
- name: install htop
  block:
  - name: install htop
    yum:
      name: htop
      state: present
  when:
    - install_htop | bool == true
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  become: true
  become_method: sudo

- block:
  - name: uninstall htop
    yum:
      name: htop
      state: absent
  when:
    - install_htop | bool == false
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  become: true
  become_method: sudo
