---
- block:

  - name: install httpd-tools
    yum:
      name: httpd-tools
      state: present

  when: install_httpd_tools | bool == true
  become: true
  become_method: sudo

- block:

  - name: uninstall httpd-tools
    yum:
      name: httpd-tools
      state: absent

  when: install_httpd_tools | bool == false
  become: true
  become_method: sudo
