---
- block:
  - name: install httpd-tools
    yum:
      name: httpd-tools
      state: present
  when:
    - install_httpd_tools | bool == true
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  become: true
  become_method: sudo

- block:
  - name: uninstall httpd-tools
    yum:
      name: httpd-tools
      state: absent
  when:
    - install_httpd_tools | bool == false
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  become: true
  become_method: sudo
