# tasks file for roles/applications
---
- name: import docker tasks
  import_tasks: docker.yml
  when: install_docker is defined
  tags:
    - docker

- name: import htop tasks
  import_tasks: htop.yml
  when: install_htop is defined
  tags:
    - htop

- name: import httpd_tools tasks
  import_tasks: httpd_tools.yml
  when: install_httpd_tools is defined
  tags:
    - httpd_tools

- name: import jq tasks
  import_tasks: jq.yml
  when: install_jq is defined
  tags:
    - jq
