---
- block:
  - name: install jq
    yum:
      name: jq
      state: present
  when:
    - apps_jq_install | bool == true
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  become: true
  become_method: sudo

- block:
  - name: uninstall jq
    yum:
      name: jq
      state: absent
  when:
    - apps_jq_install | bool == false
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  become: true
  become_method: sudo
