---
- name: install centos docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  when:
    - ansible_distribution == "CentOS"

- name: install fedora docker repo
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  when:
    - ansible_distribution == "Fedora"
