---
- name: Import docker.yml
  when: repos_docker_install is defined
  import_tasks: docker.yml
  tags:
    - repos_docker_install

- name: Import epel.yml
  when: repos_epel_install is defined
  import_tasks: epel.yml
  tags:
    - repos_epel_install
