---
- block:
  - name: copy .bashrc to ~
    copy:
      src: .bashrc
      dest: ~/.bashrc
  when:
    - deploy_bashrc | bool == true
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- block:
  - name: make sure ~/.bashrc is original from centos
    copy:
      src: .bashrc.orig
      dest: ~/.bashrc
  when:
    - deploy_bashrc | bool == false
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
